# Baseline Model Evaluation
This notebook evaluates the performance of the base instruction-tuned language model before fine-tuning.

The objective is to establish a baseline performance level and later compare it with the fine-tuned model.

In this notebook we will:

- Load the instruction-tuned transformer model.
- Load the held-out test dataset.
- Format prompts for evaluation.
- Generate predicted scores and rationales.
- Parse model outputs.
- Compare predictions with ground-truth labels.
- Save results for later analysis.

This baseline evaluation is essential to measure the actual impact of fine-tuning.

## 1. Import Libraries and Configure Environment
we import all required libraries for inference and evaluation.

In [1]:
import json
import torch
import re  
import pandas as pd
from pathlib import Path
from transformers import (AutoTokenizer , AutoModelForCausalLM)
from sklearn.metrics import accuracy_score, mean_absolute_error

print("PyTorch Version:", torch.__version__)

device = ("cuda"if torch.cuda.is_available()else "cpu")
print("Device:", device)

if device == "cuda":
    print("GPU:",torch.cuda.get_device_name(0))

PyTorch Version: 2.7.1+cu118
Device: cuda
GPU: NVIDIA A100-SXM4-80GB

## 2. Load Baseline Model
In this section, we load the pretrained instruction-tuned transformer model.

This model serves as the baseline system and will be evaluated before any additional training.

The purpose of this step is to establish a reference performance level that will later be compared with the fine-tuned version.

The model will generate:

- A score (0–4)
- A rationale explaining the evaluation

In [2]:
MODEL_NAME = ("unsloth/mistral-7b-instruct-v0.2-bnb-4bit")

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("Loading model...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto"
)

print("Model loaded successfully.")

Loading tokenizer...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Model loaded successfully.

## 3. Load Test Dataset
In this section, we load the held-out test dataset.

The test set is kept completely separate from training and validation data because its purpose is to provide an unbiased estimate of model performance.

Only the test split will be used in this notebook.

Each sample contains:

- task
- reference
- submission
- rubric
- ground-truth score
- rationale

These labels will later be compared against the model predictions.

In [3]:
test_path = Path("../data/test.jsonl")

records = []

with open(test_path,"r",encoding="utf-8") as f:
    for line in f:
        records.append(json.loads(line))

test_df = pd.DataFrame(records)

print(f"Loaded {len(test_df)} test samples.")
print("Sample test data:")
display(test_df.head(2))

Loaded 10 test samples.
Sample test data:

,task,reference,submission,rubric,score,rationale,reference_length,submission_length,rationale_length
0,Customer is requesting a refund for a product ...,We are sorry to hear that you are not satisfie...,We can process a refund for you. It will take ...,"{'1': 'Shows understanding and apology', '2': ...",2,The reply mentions a refund but gives a vague ...,46,13,27
1,Customer reports that the product they receive...,We are so sorry to hear that your product arri...,Products can get damaged during shipping. Send...,"{'1': 'Shows understanding and apology', '2': ...",1,The reply asks for a photo which is a vague hi...,49,11,34

## 4. Build Evaluation Prompt
create the prompt template used to evaluate customer support replies.

Prompt design is an important part of instruction-tuned language models because it determines how information is presented to the model and how outputs are generated.

The prompt includes:

- Task description
- Reference response
- Candidate submission
- Evaluation rubric

The model is instructed to act as an expert evaluator and generate:

- A score from 0 to 4
- A short rationale

To make outputs easier to process later, the model will be instructed to return valid JSON only.

In [4]:
def build_prompt(row):
    rubric_text = "\n".join([
        f"{k}. {v}"
        for k, v in row["rubric"].items()
    ])

    prompt = f"""
You are an expert evaluator for customer support replies.
Evaluate the quality of the submission.
Return ONLY valid JSON.

Format:
{{
    "score": integer from 0 to 4, where 0 is the worst and 4 is the best,
    "rationale": "short explanation"
}}

Task:
{row["task"]}

Reference:
{row["reference"]}

Submission:
{row["submission"]}

Rubric:
{rubric_text}
"""
    return prompt.strip()

sample_prompt = build_prompt(test_df.iloc[0])
print(sample_prompt)

You are an expert evaluator for customer support replies.
Evaluate the quality of the submission.
Return ONLY valid JSON.

Format:
{
    "score": integer from 0 to 4, where 0 is the worst and 4 is the best,
    "rationale": "short explanation"
}

Task:
Customer is requesting a refund for a product they are not satisfied with.

Reference:
We are sorry to hear that you are not satisfied with your purchase. We completely understand your frustration. We will process a full refund for you within 5 to 7 business days. Please let us know if there is anything else we can help you with.

Submission:
We can process a refund for you. It will take a few days.

Rubric:
1. Shows understanding and apology
2. Provides correct and relevant information
3. Provides clear solution or next step
4. Uses polite and professional tone

## 5. Run Baseline Inference
In this section, we run the pretrained model on the held-out test set.

For each sample:

- Build the evaluation prompt
- Generate a response
- Store the prediction

At this stage, the model has not been fine-tuned on our dataset.

The generated outputs will later be compared with the human-annotated scores.

In [5]:
def generate_response(prompt):
    inputs = tokenizer(prompt ,return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(**inputs, max_new_tokens=150, do_sample=False)

    response = tokenizer.decode(outputs[0],skip_special_tokens=True)

    return response

example = build_prompt(test_df.iloc[1])
result = generate_response(example)

print(result)

[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are an expert evaluator for customer support replies.
Evaluate the quality of the submission.
Return ONLY valid JSON.

Format:
{
    "score": integer from 0 to 4, where 0 is the worst and 4 is the best,
    "rationale": "short explanation"
}

Task:
Customer reports that the product they received is damaged and requests a replacement or refund.

Reference:
We are so sorry to hear that your product arrived damaged. We completely understand how disappointing this must be. We will send you a replacement immediately or issue a full refund, whichever you prefer. Please let us know your choice and we will take care of it right away.

Submission:
Products can get damaged during shipping. Send us a photo first.

Rubric:
1. Shows understanding and apology
2. Provides correct and relevant information
3. Provides clear solution or next step
4. Uses polite and professional tone

Evaluation:
{
    "score": 2,
    "rationale": "The response acknowledges the possibility of damage during shipping, but it does not show a clear understanding of the customer's disappointment and does not offer a direct solution or next step. Instead, it asks for a photo first, which may delay the process and create additional frustration for the customer."
}

## 6. Parse Model Output
The model output may contain extra text before the final prediction.

In this section, we extract only the JSON object containing:

- score
- rationale

This ensures that predictions can be processed automatically and compared against the ground-truth labels.

In [6]:
def extract_prediction(text):
    try:
        matches = re.findall(r"\{[\s\S]*?\}", text)
        if matches:
            last_json = matches[-1]
            return json.loads(last_json)

    except Exception:
        pass

    return {
        "score": None,
        "rationale": None
    }

parsed = extract_prediction(result)
print(parsed)

{'score': 2, 'rationale': "The response acknowledges the possibility of damage during shipping, but it does not show a clear understanding of the customer's disappointment and does not offer a direct solution or next step. Instead, it asks for a photo first, which may delay the process and create additional frustration for the customer."}

## 7. Run Evaluation on Test Set
In this step, we evaluate the model on the held-out test set.

For each sample in the test dataset:

We build a structured prompt
We generate a response using the model
We extract the predicted score and rationale
We store the results for later analysis

This allows us to compare the model’s predictions against the ground-truth labels and measure performance objectively.

In [12]:
predictions = []

for _, row in test_df.iterrows():
    prompt = build_prompt(row)
    result = generate_response(prompt)
    parsed = extract_prediction(result)

    predictions.append({
        "task": row["task"],
        "reference": row["reference"],
        "submission": row["submission"],
        "true_score": row["score"],
        "pred_score": parsed["score"],
        "rationale": parsed["rationale"]
    })

pred_df = pd.DataFrame(predictions)

print("Evaluation completed.")
display(pred_df[["true_score", "pred_score"]].head(10))

[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=150) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Evaluation completed.

   true_score  pred_score
0           2           3
1           1           2
2           3           4
3           3           4
4           4           4
5           4           4
6           1           2
7           0           1
8           2           1
9           0           0

## 8. Evaluation Metrics
Now we compute evaluation metrics to measure how close the model predictions are to the ground truth.

We use:

- Accuracy (exact match between predicted and true score)
- Mean Absolute Error (MAE)

These metrics help us understand both correctness and distance from the expected score.

In [13]:
accuracy = accuracy_score(pred_df["true_score"], pred_df["pred_score"])
mae = mean_absolute_error(pred_df["true_score"], pred_df["pred_score"])

print(f"Accuracy: {accuracy:.2f}%")
print(f"MAE: {mae:.2f}")

Accuracy: 0.30%
MAE: 0.70

## 9. Error Analysis (Incorrect Predictions Review)
In this section, we analyze the model’s mistakes to better understand its behavior.

Instead of only looking at evaluation metrics, we inspect individual samples where the model prediction differs from the ground truth.

This helps us identify:

- Common failure patterns
- Whether the model is biased toward higher or lower scores
- Cases where the rubric interpretation is unclear
- Types of responses that are difficult for the model to evaluate

Error analysis is important because it provides qualitative insight beyond numerical metrics.

In [16]:
errors_df = pred_df[pred_df["true_score"] != pred_df["pred_score"]]

print(f"Number of errors: {len(errors_df)}")
display(errors_df[["true_score", "pred_score"]].head(10))

Number of errors: 7

   true_score  pred_score
0           2           3
1           1           2
2           3           4
3           3           4
6           1           2
7           0           1
8           2           1

## 10. Visualizing Some Error Examples
Here we inspect a few misclassified examples to understand why the model made incorrect predictions.

We compare:

- True score
- Predicted score
- Model rationale

This helps us evaluate whether the mistakes are due to misunderstanding of the rubric or natural ambiguity in the data.

In [20]:
for i, row in errors_df.head(1).iterrows():
    print("=" * 80)
    print("TASK:")
    print(row["task"])
    print("\nREFERENCE:")
    print(row["reference"])
    print("\nSUBMISSION:")
    print(row["submission"])
    print("\nTRUE SCORE:", row["true_score"])
    print("PREDICTED SCORE:", row["pred_score"])
    print("\nRATIONALE:")
    print(row["rationale"])

================================================================================
TASK:
Customer is requesting a refund for a product they are not satisfied with.

REFERENCE:
We are sorry to hear that you are not satisfied with your purchase. We completely understand your frustration. We will process a full refund for you within 5 to 7 business days. Please let us know if there is anything else we can help you with.

SUBMISSION:
We can process a refund for you. It will take a few days.

TRUE SCORE: 2
PREDICTED SCORE: 3

RATIONALE:
The submission acknowledges the request for a refund but lacks a clear apology and does not provide any additional information or next steps beyond the refund process.

## 11. Save Results

In this step, we save the model predictions and evaluation results to disk.
This allows us to reuse the outputs in further analysis and fine-tuning comparison without recomputing inference.

In [21]:
output_path = Path("../data/baseline_predictions.jsonl")
pred_df.to_json(output_path, orient="records", lines=True)
print(f"Results saved to {output_path}")

Results saved to ../data/baseline_predictions.jsonl

## 12. Summary

In this notebook, we built a complete baseline evaluation system for a customer support reply scoring task using a pre-trained instruction-tuned language model.

The main goal was to measure how well a general-purpose LLM can evaluate customer support responses without any fine-tuning on our dataset, and to establish a reference point for future improvements.

### 1. Environment Setup and Model Loading

We started by:

- Importing required libraries such as PyTorch, Pandas, Transformers, and Scikit-learn.
- Checking GPU availability to ensure efficient inference.
- Loading a pre-trained instruction-tuned language model:
- Mistral 7B Instruct (4-bit quantized version for memory efficiency)

We also loaded the tokenizer to convert text into model-readable tokens.

### 2. Dataset Loading

We loaded the test dataset from a .jsonl file, where each sample contains:

- task (customer request)
- reference (ideal answer)
- submission (agent reply)
- rubric (scoring criteria)
- score (ground-truth label)
- rationale (human explanation)

We converted the dataset into a pandas DataFrame for easier processing.

### 3. Prompt Construction

We designed a structured prompt using all available fields:

- Task description
- Reference answer
- Submission
- Rubric

The goal was to guide the model to behave like an expert evaluator and return:

- A numeric score (0–4)
- A short rationale explaining the decision

This step is crucial because prompt quality directly affects LLM performance.

### 4. Model Inference

For each test sample:

- We generated a prompt
- Passed it to the model
- Generated a response using greedy decoding (no randomness)
- Extracted the final JSON output from the model response

This allowed us to automate scoring for all test samples.

### 5. Output Parsing

Since LLM outputs may contain extra text, we implemented a parsing function that:

Extracts the JSON block from the response
Retrieves:
- score
- rationale

This ensures structured and machine-readable outputs.

### 6. Evaluation

We compared predictions with ground truth labels using:

- Accuracy → exact match between predicted and true score
- MAE (Mean Absolute Error) → average distance between predicted and true score

These metrics help evaluate both strict correctness and average deviation.

### 7. Error Analysis

We analyzed incorrect predictions to:

- Identify patterns of model mistakes
- Understand ambiguity in scoring
- Inspect real examples of failures

This step provides qualitative insights beyond numerical metrics.

### 8. Results Storage

We saved all predictions (including true scores, predicted scores, and rationales) into a structured file for:

- future analysis
- fine-tuning preparation
- reproducibility

### Final Conclusion

This notebook establishes a baseline evaluation pipeline for a rubric-based customer support reply evaluator.

The results show that the base model can partially understand evaluation tasks, but it is inconsistent in assigning precise scores. This confirms the need for instruction fine-tuning (LoRA) in the next stage to align the model with our specific scoring rubric.